### ISSUE TITLE
Redis error during OAuth authentication

### ISSUE THREAD

**Issue by vprivat-ads** [toolforge/video2commons#187] opened 2024-02-29 10:26 UTC
https://video2commons.toolforge.org/oauthinit?returnto=https%3A%2F%2Fvideo2commons.toolforge.org%2F

gives:

```
Please file an issue in GitHub: 
Traceback (most recent call last): 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request return self.finalize_request(rv) 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1540, in finalize_request response = self.process_response(response) 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1888, in process_response self.session_interface.save_session(self, ctx.session, response) 
File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/redisession.py", line 98, in save_session self.redis.setex(self.prefix + session.sid, 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/client.py", line 1822, in setex return self.execute_command('SETEX', name, time, value) 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command return self.parse_response(conn, command_name, **options) 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response response = connection.read_response() 
File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response raise response redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. 
```

**Comment by royjor2016** [comment] 2024-03-02 19:24
it seems the bug has been resolved by itself?

**Comment by don-vip** [comment] 2024-04-27 09:53
Yep, the issue is no longer there.

**Closed by don-vip** 2024-04-27 09:53 UTC
